config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :maps
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]

  root  'static_pages#home'

  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'

  get '*path' => redirect('/')
end

app/models/message.rb
class Message < ActiveRecord::Base

  has_attached_file :image,
                    validate_media_type: false,
                    styles: { thumb: ["140x140#", :jpg],
                              original: ['500x500>', :jpg]}
  #do_not_validate_attachment_file_type :image
  validates_attachment :image, presence: true,
                       content_type: { content_type: ["image/jpeg", "image/jpg", "image/gif", "image/png"] }

  default_scope -> { order('created_at DESC') }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:destroy, :edit]


  # GET /messages
  # GET /messages.json
  def index
    session[:isMainPage] = 'false'
    @messages = Message.all
    @message_items = Message.paginate(page: params[:page], per_page: 4)
    @message_controller = true
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    session[:isMainPage] = 'false'

    respond_to do |format|
      if @message.save

        format.html { redirect_to @message, info: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    session[:isMainPage] = 'false'
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, info: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, info: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:user_id, :name, :description, :image)
    end


  def admin_user
    redirect_to(root_url) unless current_user && current_user.admin?
  end


end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for @message, html: {multipart: true} do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control'%>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description , class: 'form-control'%>
  </div>

  <div class="field">
    <%= f.label :image %><br/>
    <% if @message.image.file?%>
        <%= link_to image_tag(@message.image.url(:thumb), class: 'media-object'), @message.image.url, target: '_blank' %>
    <% end %>
  </div>

    <div class="field">
      <%= f.label :image, 'Select File', class: 'control-label' %>
      <%= f.file_field :image, class: 'file', 'multiple data-show-upload' => false, 'data-show-caption' => true %><br>
    </div>
    <br>
  <div>
    <%= f.submit nil, class: 'btn btn-primary', style: 'width:140px' %>
  </div>
    <br/>
    <br/>
<% end %>

app/views/messages/edit.html.erb
<!--<script>
    $(document).on('ready', function () {
        $("#input-2").fileinput();
    });
</script>-->
<h1>Editing message</h1>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= render 'form' %>
    </div>
  </div>
</div>


<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>News List</h1>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
        <%= link_to 'New Message', new_message_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

<%= render 'shared/message' %>

<br/>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'New Message', new_message_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/messages/new.html.erb
<%= javascript_include_tag 'fileinput.js' %>
<%= stylesheet_link_tag    'fileinput' %>
<script>
    $(document).on('ready', function () {
        $("#message_image").fileinput();
    });
</script>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
        <h1>New message</h1>

        <%= render 'form' %>

    </div>
  </div>
</div>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h2><%= @message.name %></h2>

      <p>
          <%= link_to image_tag(@message.image.url(:original), class: 'media-object img-rounded leftimg'), target: '_blank' %>
          <%= @message.description %>
      </p>


    </div>
    </br>
    <% if session[:isMainPage] == 'false' %>
        <%= link_to 'Back', messages_path %>
    <% else %>
        <%= link_to 'Back', root_path %>
    <% end %>
  </div>
</div>