config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :maps
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]

  root  'static_pages#home'

  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'

  get '*path' => redirect('/')
end

app/models/map.rb
class Map < ActiveRecord::Base

  belongs_to :user

  has_attached_file :image,
                    validate_media_type: false,
                    styles: { thumb: ["140x140#", :jpg],
                              original: ['2000x2000>', :jpg]}
  #do_not_validate_attachment_file_type :image
  validates_attachment :image, presence: true,
                       content_type: { content_type: ["image/jpeg", "image/jpg", "image/gif", "image/png"] }

  default_scope -> { order('created_at DESC') }


end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
#    @maps = Map.all
    @user = current_user
    #@maps = @user.maps.paginate(page: params[:page], per_page: 3)
    @map_items = @user.maps.paginate(page: params[:page], per_page: 3)
  end


  # GET /maps/1
  # GET /maps/1.json
  def show
    @map = Map.find(params[:id])
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, info: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, info:  'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params[:map] = params[:map].merge(:user_id => current_user.id)
      params.require(:map).permit(:name, :user_id, :image, :description, :cp_number)
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<%= form_for @map, html: {multipart: true} do |f| %>
    <% if @map.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">
            <h2><%= pluralize(@map.errors.count, "error") %> prohibited this message from being saved:</h2>
            <ul>
              <% @map.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: 'form-control'%>
    </div>

    <div class="field">
      <%= f.label :cp_number %><br>
      <%= f.number_field :cp_number, class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :image %><br/>
      <% if @map.image.file? %>
          <%= link_to image_tag(@map.image.url(:thumb), class: 'media-object'), @map.image.url, target: '_blank' %>
      <% end %>
    </div>

    <div class="field">
      <%= f.label :image, 'Select File', class: 'control-label' %>
      <%= f.file_field :image, class: 'file', 'multiple data-show-upload' => false, 'data-show-caption' => true %><br>
    </div>
    <br/>

    <div>
      <%= f.submit nil, class: 'btn btn-primary', style: 'width:140px' %>
    </div>
    <br/>
    <br/>

<% end %>

app/views/maps/_map.html.erb
<li>

  <span class="content"><%= map.name %></span>
  <span class="content"><%= map.description %></span>
  <span class="content">Control points : <%= map.cp_number %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(map.created_at) %> ago.
  </span>
  <% if current_user?(map.user) %>
      <%= link_to "delete", map, method: :delete,
                  data: { confirm: "You sure?" },
                  title: map.name %>
  <% end %>
</li>

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= render 'form' %>
    </div>
  </div>
</div>


<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<h1>Maps List</h1>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'Add Map', new_map_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

<%= render 'shared/map' %>

<br/>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'Add Map', new_map_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h2><%= @map.name %></h2>

      <p>
        <%= link_to image_tag(@map.image.url(:thumb), class: 'media-object img-rounded leftimg'), @map.image.url, target: '_blank' %>
        <%= @map.description %>
        <br>
        <strong>Cp number:</strong>
        <%= @map.cp_number %>
      </p>

    </div>
    </br>

        <%= link_to 'Back', maps_path %>

  </div>
</div>