config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :maps
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]

  root  'static_pages#home'

  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'

  get '*path' => redirect('/')
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
      <%= render partial: 'shared/feed_item', collection: @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
      <%= link_to 'delete', feed_item, method: :delete,
                  data: { confirm: 'You sure?' },
                  title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_map.html.erb
<% if @map_items.any? %>

    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">



          <div class="digg_pagination"> <%= will_paginate @map_items %> </div>
                <%= render partial: 'shared/map_item', collection: @map_items %>
          <div class="digg_pagination"> <%= will_paginate @map_items %> </div>

        </div>
      </div>
    </div>


<% end %>

app/views/shared/_map_item.html.erb
<div class="row row-newspage">
  <div class="col-md-2">
    <%= link_to image_tag(map_item.image.url(:thumb), class: 'media-object img-rounded'), maps_path + '/' + map_item.id.to_s, class: 'btn', style: 'padding: 0px 0px' %>
    <div class="timestamp">
      Added <%= time_ago_in_words(map_item.created_at) %> ago.
    </div>
  </div>
  <div class="col-md-10">
    <h2><%= map_item.name %></h2>
    <% if (map_item.description.size > 200)%>
        <p>
          <%= map_item.description[0,200] %>...
        </p>
    <% else %>
        <p>
          <%= map_item.description %>
        </p>
    <% end %>
    <p>
      <b>Control points: </b><%= map_item.cp_number %>
    </p>
  </div>
  <% if (current_user) %>
      <p>
        <%= link_to ApplicationHelper::EDIT_LINK, edit_map_path(map_item), class: 'btn' %>
        <%= link_to ApplicationHelper::DELETE_LINK, map_item, class: 'btn', method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
  <% end %>

</div>

app/views/shared/_message.html.erb
<% if @message_items.any? %>

    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">



          <div class="digg_pagination"> <%= will_paginate @message_items %> </div>
                <%= render partial: 'shared/message_item', collection: @message_items %>
          <div class="digg_pagination"> <%= will_paginate @message_items %> </div>

        </div>
      </div>
    </div>


<% end %>

app/views/shared/_message_item.html.erb
<div class="row row-newspage">
  <div class="col-md-2">
    <%= link_to image_tag(message_item.image.url(:thumb), class: 'media-object img-rounded'), messages_path + '/' + message_item.id.to_s, class: 'btn', style: 'padding: 0px 0px' %>
    <div class="timestamp">
      Posted <%= time_ago_in_words(message_item.created_at) %> ago.
    </div>
  </div>
  <div class="col-md-10">
    <h2><%= message_item.name %></h2>

    <% if (message_item.description.size > 200)%>
        <p>
          <%= message_item.description[0,200] %>...
        </p>
    <% else %>
        <p>
          <%= message_item.description %>
        </p>
    <% end %>
  </div>
  <% if (current_user && current_user.admin && @message_controller != nil) %>
      <p>
        <%= link_to ApplicationHelper::EDIT_LINK, edit_message_path(message_item), class: 'btn' %>
        <%= link_to ApplicationHelper::DELETE_LINK, message_item, class: 'btn', method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
  <% else %>
      <p>
        <a class="btn" href="<%= messages_path %>/<%= message_item.id %>">View details....</a>
      </p>
  <% end %>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to ApplicationHelper::VIEW_PROFILE_LINK, current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>