config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :maps
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]

  root  'static_pages#home'

  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'

  get '*path' => redirect('/')
end

app/views/layouts/_footer.html.erb
<footer class="footer">

  <nav>
    <ul>
      <li><%= link_to ApplicationHelper::ABOUT_LINK, about_path %></li>
      <li><%= link_to ApplicationHelper::CONTACT_LINK, contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to ApplicationHelper::APP_NAME, root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>
              <% if current_user.admin %>
                  <li><%= link_to ApplicationHelper::MESSAGES, messages_path %></li>
                  <li><%= link_to ApplicationHelper::USERS_LINK_NAME, users_path %></li>
              <% end %>

              <li><%= link_to ApplicationHelper::MAPS_LINK_NAME, maps_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account
                  <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to ApplicationHelper::PROFILE_MENU_NAME,  current_user %></li>
                  <li><%= link_to ApplicationHelper::SETTINGS_MENU_NAME, edit_user_path(current_user) %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to ApplicationHelper::SIGN_OUT_LINK, signout_path %></li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to ApplicationHelper::HELP, help_path %></li>
              <li><%= link_to ApplicationHelper::SIGN_IN, signin_path %></li>
          <% end %>

        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>

</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= ApplicationHelper::APP_NAME %> | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'fileinput.js' %>
  <%= stylesheet_link_tag    'fileinput' %>

  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>


<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>


  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>